// Code generated by "stringer -type=errParseFlag"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errNotEnoughArgs-0]
	_ = x[errNonMatchingFlags-1]
	_ = x[errZeroFlagName-2]
	_ = x[errIncorrectflagPrefix-3]
	_ = x[errMissingTemplateFlag-4]
}

const _errParseFlag_name = "errNotEnoughArgserrNonMatchingFlagserrZeroFlagNameerrIncorrectflagPrefixerrMissingTemplateFlag"

var _errParseFlag_index = [...]uint8{0, 16, 35, 50, 72, 94}

func (i errParseFlag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_errParseFlag_index)-1 {
		return "errParseFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errParseFlag_name[_errParseFlag_index[idx]:_errParseFlag_index[idx+1]]
}
